import type { Metadata } from "next";
import { Germania_One, Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./component/layout/nav-bar";
import Footer from "./component/footer";


const inter = Inter({ subsets: ["latin"] });
const germaniaOne = Germania_One({ subsets: ["latin"], weight: ["400"],   variable: "--germania"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${germaniaOne.variable}`}>
        <NavBar/>
        <div className='min-h-[70svh]'> {children}</div>
        < Footer />
        </body>
    </html>
  );
}
